app:
  debug: true
  secret: ""
  grpc:
    tsl: false
    port: 8080

db:
  enabled: false
  driver: postgres
  host: 127.0.0.1
  port:
    in: 5432 # don't change it (port inside docker)
    out: 5431  # available for outer connections
  name: postgres
  user: postgres
  pass: secret

storage:
  path: ./storage

jobs:
  enabled: false

kafka:
  enabled: false
  brokers: