version: "3.7"
services:

  postgres:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_PASSWORD: qwerty
    ports:
      - "5431:5432"
    volumes:
      - ./storage/database/postgres:/var/lib/postgresql/data
      - ./setup/initdb.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - fullstack

  microservice:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./setup/wait-for-postgres.sh ./app/server
    depends_on:
      - postgres
    ports:
      - "8071:8071"
    networks:
      - fullstack
    environment:
#      - DB_HOST=host.docker.internal
      - DB_HOST=postgres
      - DB_NAME=postgres
      - DB_PASS=qwerty

networks:
  fullstack:
    driver: bridge
